Repository uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes, pull requests merged in 2024-11, with the labels that each got.

#284 Removed gameMode, switched to lobby
  frontend/src/App.js
  frontend/src/Auth/Login.js
  frontend/src/gameMode.js
  frontend/src/gamestate/AdvancedBot.js
  frontend/src/gamestate/Bot.js
  frontend/src/gamestate/advancedtester.test.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestate/table.js
  frontend/src/lobby/lobby.css
  frontend/src/lobby/lobby.js
Labels: enhancement, UI/UX, Gameplay/AI, Auth/Player/Online

#344 Added the new asset and implemented it
  frontend/public/New-Dominos-28-Horrizontally.png
  frontend/public/new-backtile.png
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#339 Completed the modifications
  frontend/src/Home/Home.css
  frontend/src/Home/Home.js
Labels: UI/UX

#347 Enhanced Lobby Screens
  frontend/src/lobby/lobby.css
  frontend/src/lobby/lobby.js
Labels: UI/UX

#354 added documentation to the Rule engine md
  frontend/src/gamestate/ruleEngine.md
Labels: Gameplay/AI

#352 Modified buttons and text in Game State to match game aesthetic
  frontend/src/App.css
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#357 created markdown documentation for the bot classes.
  frontend/src/gamestate/Bots.md
Labels: documentation

#358 Added unit tests for drawDominoes game mode.
  frontend/src/App.test.js
  frontend/src/gamestate/RuleEngine.js
Labels: Gameplay/AI

#341 Incremented JWT security and fixed functionality
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/UsersController.js
  backend/src/handlers/UsersHandler.js
  backend/src/index.js
  backend/src/middleware/authenticateJWT.js
Labels: Auth/Player/Online

#376 Added Contact Us, FAQs, and Privacy Policy pages with routing.
  frontend/src/App.js
  frontend/src/Home/ContactUs.js
  frontend/src/Home/FAQS.js
  frontend/src/Home/Home.js
  frontend/src/Home/PrivacyPolicy.js
Labels: UI/UX

#379 created markdown documentation for experimental game
  frontend/src/gamestate/experimentalGame.md
Labels: documentation

#393 Add more error handling for the mismatch JWT secret keys and added a Admin role to the User model and modify the timeout timers
  backend/package-lock.json
  backend/package.json
  backend/src/handlers/UsersHandler.js
  backend/src/models/UserModel.js
  backend/src/routes/authRoutes.js
Labels: Auth/Player/Online

#392 Add player avatars and improve game layout
  frontend/public/Blue-Avatar.PNG
  frontend/public/Green-Avatar.PNG
  frontend/public/Red-Avatar.PNG
  frontend/public/Yellow-Avatar.PNG
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#397 12-fixed-game-buttons
  frontend/src/App.css
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#402 Improving Domino Visuals and Orientation
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestate/table.js
Labels: Gameplay/AI

#406 Created markdown documentation for chat popup in Multiplayer dominoes.
  frontend/src/gamestate/Chat.md
Labels: documentation

#407 Created markdown document for table class.
  frontend/src/gamestate/table.md
Labels: documentation

#400 Render rules and instructions when clicking on "Instruction" links in the Home Page
  frontend/src/Home/Home.css
  frontend/src/Home/Home.js
Labels: UI/UX

#409 Add “Back To Home” Button to Contact Us Page
  frontend/src/Home/ContactUs.js
  frontend/src/Home/FAQS.js
  frontend/src/Home/Home.css
  frontend/src/Home/PrivacyPolicy.js
Labels: UI/UX

#411 Re-design lobby button functionality and look
  frontend/src/App.css
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#412 408 finishing UI sounds implementations
  frontend/public/GamestateSound.wav
  frontend/public/SelectionSound.wav
  frontend/src/App.js
  frontend/src/Auth/ForgotPassword.js
  frontend/src/Auth/Login.js
  frontend/src/Home/Home.js
  frontend/src/gamestate/Pause.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/lobby/lobby.js
Labels: UI/UX

#398 Specification patterns added
  backend/src/controllers/RoomsController.js
  backend/src/controllers/UsersController.js
  backend/src/specifications/RoomSpecification.js
  backend/src/specifications/UserSpecification.js
Labels: documentation, Auth/Player/Online

#413 added a md file for achivements
  frontend/src/gamestate/AchievementManager.md
Labels: Gameplay/AI

#394 Profile page Customzation
  backend/public/BlueAvatar.png
  backend/public/BlueProfile.png
  backend/public/GreenAvatar.png
  backend/public/OrangeProfile.png
  backend/public/RedAvatar.png
  backend/public/YellowAvatar.png
  backend/public/default-profile.png
  backend/src/index.js
  backend/src/middleware/authenticateJWT.js
  backend/src/models/UserModel.js
  backend/src/repositories/UserRepository.js
  backend/src/routes/authRoutes.js
  backend/src/routes/userRoutes.js
  frontend/public/BlueAvatar.png
  frontend/public/BlueProfile.png
  frontend/public/GreenAvatar.png
  frontend/public/OrangeProfile.png
  frontend/public/RedAvatar.png
  frontend/public/YellowAvatar.png
  frontend/public/default-profile.png
  frontend/public/editIcon.png
  frontend/src/App.js
  frontend/src/Auth/Login.js
  frontend/src/Auth/ProfilePage.css
  frontend/src/Auth/ProfilePage.js
  frontend/src/Auth/hooks/useUserData.js
  frontend/src/Home/Home.css
  frontend/src/Home/Home.js
Labels: Auth/Player/Online

#416 Added Lobby Id generation, server functionaliy and invites
  frontend/client.js
  frontend/package-lock.json
  frontend/package.json
  frontend/server.js
  frontend/src/App.js
  frontend/src/gamestate/multi.js
  frontend/src/lobby/lobby.css
  frontend/src/lobby/lobby.js
  frontend/src/lobby/socket.js
Labels: Auth/Player/Online

#418 Added background implementation
  frontend/build/M3-board1.png
  frontend/build/M3-board2.png
  frontend/build/M3-board3.png
  frontend/public/M3-board1.png
  frontend/public/M3-board2.png
  frontend/public/M3-board3.png
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX
