Repository uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes, pull requests merged in 2024-09, with the labels that each got.

#75 Domino Base Game Logic
  package.json
  src/App.js
  src/gamestate/experimentalGame.js
  src/gamestate/table.js
  src/index.js
Labels: Gameplay/AI

#72 Created backend skeleton
  .gitignore
  README.md
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/HealthCheckController.js
  backend/src/controllers/UsersController.js
  backend/src/database/MongoDbConnection.js
  backend/src/handlers/UsersHandler.js
  backend/src/index.js
  backend/src/models/UserModel.js
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestate/table.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: Auth/Player/Online

#76 11 basic game ai implementation
  frontend/src/gamestate/Bot.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI

#99 Initial login/signup form implementation
  frontend/package.json
  frontend/public/images/logo_with_name.png
  frontend/src/App.js
  frontend/src/Auth/Login.css
  frontend/src/Auth/Login.js
Labels: Auth/Player/Online

#103 Adding save system for multiplayer dominoes to main.
  backend/src/gamestatus/GameStatus.js
Labels: Gameplay/AI

#101 Browser favicon and title update
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
Labels: enhancement

#107 30 - Pause screen with "Resume Game" and "Back to login" buttons.
  frontend/src/App.js
  frontend/src/gamestate/Pause.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI

#114 #69 achievement manager and #67 Rule engine
  frontend/package-lock.json
  frontend/package.json
  frontend/src/gamestate/AchievementManager.js
  frontend/src/gamestate/Bot.js
  frontend/src/gamestate/RuleEngine.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI

#106 Implemented the visibility of the rules
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.js
Labels: UI/UX

#119 15 - Added unit testing
  frontend/src/App.test.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI, Testing

#113 Add Authentication and Registration endpoints. Add dummy data to User…
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/UsersController.js
  backend/src/handlers/UsersHandler.js
  backend/src/index.js
  backend/src/middleware/authenticateJWT.js
  backend/src/models/UserModel.js
  backend/src/tablesData/dummyData.js
Labels: Auth/Player/Online

#117 Rooms backend logic
  backend/src/controllers/RoomsController.js
  backend/src/models/RoomsModel.js
Labels: Auth/Player/Online

#124 Changes to deploy backend server
  backend/.gitignore
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/index.js
  backend/vercel.json
Labels: Auth/Player/Online

#127 Transitioned and finished Score System over with a new synced main branch
  backend/src/gamestatus/GameStatus.js
  backend/src/gamestatus/GameStatus.test.js
Labels: Gameplay/AI

#128 Integrated Mouse Interactions (Domino Click | Table Click)
  backend/src/gamestatus/GameStatus.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI
