Repository uprm-inso4116-2024-2025-s1/semester-project-multiplayer-dominoes, pull requests merged in 2024-10, with the labels that each got.

#165 Integration of Login form with backend service
  backend/package.json
  backend/src/index.js
  frontend/src/Auth/Login.js
  frontend/src/Auth/config.js
Labels: Auth/Player/Online

#176 Creation of the IntermediateBot
  frontend/src/gamestate/Bot.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestate/intermediateBot.js
Labels: Gameplay/AI

#208 156 - Screen to choose game mode.
  frontend/src/App.js
  frontend/src/Auth/Login.js
  frontend/src/gameMode.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI

#211 Translate Table Class Comments
  frontend/src/gamestate/table.js
Labels: Gameplay/AI

#214 Login.js Unit Testing
  .gitignore
  frontend/package.json
  frontend/src/Auth/Login.test.js
Labels: Auth/Player/Online

#217 Adding comments that explain the Game Status class
  backend/package.json
  backend/src/gamestatus/GameStatus.js
  backend/src/index.js
  frontend/src/App.css
  frontend/src/App.test.js
  frontend/src/gamestate/experimentalGame.js
  package-lock.json
Labels: documentation

#206 Error handling implemented
  backend/package-lock.json
  backend/src/controllers/UsersController.js
  backend/src/handlers/UsersHandler.js
Labels: Auth/Player/Online

#209 Implementation of domino tiles assets #163
  frontend/public/Dominos-28-Horrizontally.png
  frontend/public/backtile.png
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#213 Implemented clicking sound for when a player joins a new lobby or when they view the rules
  frontend/public/DominoesClick.wav
  frontend/src/App.js
  frontend/src/lobby/lobby.js
Labels: UI/UX

#221 Unit test for achivementManager
  frontend/src/gamestate/AchievementManager.test.js
Labels: Gameplay/AI

#218 Implemented the UI sound for when a domino is placed
  frontend/public/DominoPlacement.wav
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#223 Implemented Game Overlays
  frontend/public/loser.png
  frontend/public/winner.png
  frontend/public/yourTurn.png
  frontend/src/App.css
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#222 Added Home Page with the Header and the Footer
  frontend/src/App.js
  frontend/src/Home/Home.css
  frontend/src/Home/Home.js
Labels: UI/UX

#228 Fix both issues from Domino Asset , extra domino selecting issue #226
  frontend/public/Dominos-28-Horrizontally.png
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#231 Fixed bug when going from lobby to game and added alert when going from game to lobby (player will lose progress).
  frontend/src/gamestate/experimentalGame.js
  frontend/src/lobby/lobby.js
Labels: Gameplay/AI

#233 Solid Principles on Login components. Updated UI [173,232]
  frontend/src/Auth/Login.css
  frontend/src/Auth/Login.js
  frontend/src/Auth/__test__/Login.test.js
  frontend/src/Auth/services/AuthService.js
  frontend/src/Auth/services/IAuthService.js
  frontend/src/Auth/styles/Login.css
Labels: Auth/Player/Online

#242 Applied visual design to the lobby consistent with the game's color palette
  frontend/src/lobby/lobby.css
Labels: UI/UX

#251 Enhanced the Pause Menu
  frontend/public/gamePaused.png
  frontend/src/App.css
  frontend/src/gamestate/Pause.js
Labels: UI/UX

#252 Lobbysettings
  frontend/src/gameMode.js
  frontend/src/lobby/lobby.css
  frontend/src/lobby/lobby.js
Labels: Auth/Player/Online

#257 Refactored start up to leverage SOLID principles.
  backend/package-lock.json
  backend/src/controllers/UsersController.js
  backend/src/database/MongoDbConnection.js
  backend/src/di/container.js
  backend/src/index.js
  backend/src/routes/authRoutes.js
  backend/src/routes/healthzRoutes.js
  backend/src/routes/index.js
  backend/src/routes/userRoutes.js
Labels: Auth/Player/Online

#256 Added the options to play against up to 3 bots and fixed how tiles are shown.
  frontend/src/gameMode.js
  frontend/src/gamestate/RuleEngine.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestate/table.js
Labels: Gameplay/AI

#260 Achievements assets added
  frontend/public/AllDoubles.png
  frontend/public/Cleansweep.png
  frontend/public/Dominodouble_achievement.png
  frontend/public/DoubleSix.png
  frontend/public/FirstWinAchievement.png
  frontend/src/gamestate/AchievementManager.js
  frontend/src/gamestate/experimentalGame.js
Labels: UI/UX

#255 Fix secret key from jwt
  backend/README.md
  backend/src/handlers/UsersHandler.js
  backend/src/index.js
  backend/src/middleware/authenticateJWT.js
Labels: Auth/Player/Online

#263 Five achivements
  frontend/src/gamestate/AchievementManager.js
  frontend/src/gamestate/AchievementManager.test.js
  frontend/src/gamestate/experimentalGame.js
Labels: Gameplay/AI

#265 Created Repositories in backend
  backend/src/controllers/UsersController.js
  backend/src/di/container.js
  backend/src/handlers/UsersHandler.js
  backend/src/models/RoomsModel.js
  backend/src/models/UserModel.js
  backend/src/repositories/AchievementRepository.js
  backend/src/repositories/MatchRepository.js
  backend/src/repositories/RoomRepository.js
  backend/src/repositories/UserRepository.js
Labels: Auth/Player/Online

#268 Chatui
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/gamestate/Chat.js
Labels: Auth/Player/Online

#274 Backend Unit Test for User Handler
  backend/package-lock.json
  backend/package.json
  backend/src/handlers/__test__/UserHandler.test.js
Labels: Testing

#212 Adding feature to save game through webpage refreshes
  frontend/src/App.css
  frontend/src/App.test.js
  frontend/src/gamestate/experimentalGame.js
  frontend/src/gamestatus/GameStatus.js
  frontend/src/gamestatus/GameStatus.test.js
  package-lock.json
  package.json
  src/App.js
Labels: Gameplay/AI

#264 Password Reset functionality added
  backend/README.md
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/UsersController.js
  backend/src/handlers/UsersHandler.js
  backend/src/routes/authRoutes.js
  frontend/README.md
  frontend/src/App.js
  frontend/src/Auth/ForgotPassword.js
  frontend/src/Auth/Login.js
  frontend/src/Auth/ResetPassword.js
  frontend/src/Auth/styles/Login.css
Labels: Auth/Player/Online
